### ISSUE TITLE
[ShortModal] クローズボタンが見切れる

### ISSUE THREAD

**Issue by kawamataryo** [lapras-inc/lapras-frontend#162]
ShortModalのコンテンツが多い時にクローズボタンが見切れる。
コンテンツの上部paddingを調整することで、対応したい。

![image](https://user-images.githubusercontent.com/11070996/170905041-f1dac7bf-a5d1-4ad3-9c5b-208c66c2780f.png)

![image](https://user-images.githubusercontent.com/11070996/170905047-a9fcf454-b8d0-438d-978b-8037344e01b9.png)

**Comment by Masa-Shin** [comment]
修正されたためクローズ
<img width="764" alt="スクリーンショット 2023-09-05 17 06 26" src="https://github.com/lapras-inc/lapras-frontend/assets/34234442/18648022-bcf1-47df-bb0e-161bbc9967f5">
